### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by wangwei145632** [icarofua/siamese-two-stream#2]
Thank you for your code
where is dataset1_1.json?
I run this line "python siamese_test.py siamese_original_two_stream.h5 dataset1_1.json",this dataset1_1.json don't exist,I replace dateset_1.json which is other dataset;but it occurs error:
Traceback (most recent call last):
  File "siamese_test.py", line 12, in <module>
    tst = data['tst']
KeyError: 'tst'

**Comment by icarofua** [comment]
Sorry for this. I imported in the github the dataset1_10.json.
